stages:
  - lint

Lint Python:
  stage: lint
  image: python:3.9
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run black --check .
    - poetry run flake8 --version
    - poetry run flake8 --max-line-length 100
    - poetry run mypy --strict tunnel.py
